name: Test program
on: workflow_dispatch
jobs:
  test_my_program:
    runs-on: ubuntu-latest
    steps:
      - name: Test my program
        uses: actions/checkout@v3
      - name: Install depend
        uses: actions/setup-python@v2 
      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/
