name: Test program
on: workflow_dispatch
jobs:
  test_my_program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Settings python
      - uses: action/setup-python@v5
        with: python-version:'3.13'
      - name: Установка зависимостей
        run: pip install -r requirements.txt
      - name: запуск pytest
        run: pytest/tests