name: Test program
on: workflow_dispatch
jobs:
  test_my_program:
    runs-on: python
    steps:
      - name: Test my program
        uses: actions/checkout@v3
      - name: Install depend
        run: tests/requirements.txt
      - name: Run test
        run: tests/test_api.py
