name: Test program
on: workflow_dispatch
jobs:
  test_my_program:
    runs-on: ubuntu-latest
    steps:
      - name: Test my program
        uses: actions/checkout@v3
      - name: Install depend
        run: echo hello 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run tests
        run: tests/test_api.py
