name: Test program
on: workflow_dispatch
jobs:
  test_my_program:
    runs-on: ubuntu-latest
    steps:
      - name: Test my program
        uses: actions/checkout@v3
      - name: Install depend
        run: npm ci
      - name: Lint
        run: npm run lint
